### ISSUE TITLE
Tag Markup Includes Dashes

### ISSUE THREAD

**Issue by BryanSchuetz** [ginfuru/vscode-jekyll-snippets#12]
Why are there errant dashes in the tag output. e.g.: `{%- -%}`

As far as I know liquid tags should be formatted like this: `{% %}`

**Comment by BryanSchuetz** [comment]
Looks like this was added in a [recent commit](https://github.com/ginfuru/vscode-jekyll-snippets/commit/fce949ed7cebe91cd5432d78f13df81686488087#diff-c9ad91e508b9a70726b643d290b79433) referencing "whitespace control". I don't know about all that—but I don't want these dashes in my tags.

**Comment by edheltzel** [comment]
If you're using a lot of Liquid looping or conditional logic you'll notice a lot of white space in the generated HTML. 


The `{%- -%}` removes the unnecessary  spacing, in the generated HTML... Using the tags, does not change anything regarding how Liquid/Jekyll work... **So I don't see an issue here.**

Also, as of Liquid v4.0 [white space control](https://shopify.github.io/liquid/basics/whitespace/ ) was introduced, which is also supported by Jekyll and GitHub Pages because the GitHub Pages gem enforces this version of Liquid as a [dependency](https://pages.github.com/versions/)

**Comment by BryanSchuetz** [comment]
Ah! Didn't realize whitespace trimming was even a thing. Nice, I'm all for it then—thanks.
