### ISSUE TITLE
allow snippets to run regardless of language mode

### ISSUE THREAD

**Issue by Haroenv** [ginfuru/vscode-jekyll-snippets#7]
or maybe just add markdown? I don’t know the syntax, do I duplicate the entry or is there an “OR” syntax?

**Comment by edheltzel** [comment]
Its just `JSON` if you wanna target multi language support you'll have to dig into the VSCode extension docs. Its doable and really should be pretty easy -- ~~Time is just a little hard to come by for myself.~~ 

Here is the → [API docs](https://code.visualstudio.com/Docs/extensionAPI/overview)

**Comment by edheltzel** [comment]
**I went ahead and added the support to Markdown** You can always turn it off inside of your workspace settings. 
@Haroenv ~~if you wanna clone the branch `feature/#7-markdown-support` to your `.vscode/extensions` path and try it out. 
**The snippets should work inside of markdown files.** -- _Let me know if that is what you're looking for?_~~

If your issue is remembering to set `liquid` for `HTML` files, you could always include a `.vscode/settings.json` inside of you Jekyll projects so the editor does the setting for you.
 
This is what I've been using in my Jekyll projects.
```json
{
  "files.exclude": {
    "**/.sass-cache/": true,
    "**/_site/": true
  },
  "files.associations": {
    "*.html": "liquid"
  },
  "search.exclude": {
    "**/.sass-cache/": true,
    "_site/**": true,
    ".vscode/**": true,
    "*.lock": true
  }
}

```
